name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      - name: Install Git
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          sudo apt-get install -y gcc libc6-dev

      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@latest

      - name: Build server
        env:
          GOPROXY: direct
          GONOSUMDB: "*"
          GOSUMDB: off
        run: cd server && go mod tidy && templ generate && go build -v cmd/.

      - name: Test server
        env:
          GOPROXY: direct
          GONOSUMDB: "*"
          GOSUMDB: off
        run: cd server && go test -v ./tests/...
