name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.24"

      - name: Install Git
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          sudo apt-get install -y gcc libc6-dev

      - name: Build app
        env:
          GOPROXY: direct
          GONOSUMDB: "*"
          GOSUMDB: off
        run: go mod tidy && go build -v cmd/.

      - name: Run tests
        env:
          GOPROXY: direct
          GONOSUMDB: "*"
          GOSUMDB: off
        run: go test -v ./tests/...
