// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.754
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/rangodisco/zelby/server/types"

func Home(summary types.SummaryResponse) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Zelby web dashboard</title><link href=\"https://cdn.jsdelivr.net/npm/daisyui@4.12.10/dist/full.min.css\" rel=\"stylesheet\" type=\"text/css\"><link href=\"https://cdn.jsdelivr.net/npm/remixicon/fonts/remixicon.css\" rel=\"stylesheet\" type=\"text/css\"><script src=\"https://cdn.tailwindcss.com\"></script><script>\n        tailwind.config = {\n            theme: {\n                extend: {\n                    colors: {\n                        primary: \"#085CA7\",\n                        \"primary-content\": \"#FFFFFFD8\",\n                        secondary: \"#BFAE71\",\n                        \"secondary-content\": \"#0d0b04\",\n                        accent: \"#DC8850\",\n                        \"accent-content\": \"#110602\",\n                        neutral: \"#1C1C1C\",\n                        \"neutral-content\": \"#cccccc\",\n                        \"base-100\": \"#000000\",\n                        \"base-200\": \"#1C1C1C\",\n                        \"base-300\": \"#000000\",\n                        \"base-content\": \"#bebebe\",\n                        info: \"#2563EB\",\n                        \"info-content\": \"#d2e2ff\",\n                        success: \"#52B45C\",\n                        \"success-content\": \"#020c03\",\n                        warning: \"#FFCA11\",\n                        \"warning-content\": \"#160f00\",\n                        error: \"#F35248\",\n                        \"error-content\": \"#140202\",\n                    },\n                },\n            }\n        }\n    </script></head><body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Navbar().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"container mx-auto py-4 bg-base-100 min-h-screen flex flex-col gap-6\"><!--    <h1 class=\"text-3xl font-bold mb-4 text-primary\">Zelby</h1>--><section class=\"pl-6\"><div class=\"flex w-full justify-between pb-4\"><div><h6 class=\"text-xs\">Mercredi 31 Juillet</h6><h5 class=\"text-base-content\">Résumé</h5></div><div class=\"flex\"><button class=\"btn btn-ghost btn-sm\"><i class=\"text-xl text-base-content ri-calendar-fill\"></i></button></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Summary(summary).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Graphs().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Workouts(summary.Workouts).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><script src=\"https://unpkg.com/htmx.org@1.9.10\"></script><script src=\"https://unpkg.com/htmx.org/dist/ext/json-enc.js\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
